### ISSUE TITLE
[Feature request] Изменить информацию в настройках

### ISSUE THREAD

**Issue by spanchy** [Jenstel/Kinopoisk.bundle#1]
Добавить канал обновлений плагина ваш, и проверить корректность работы. Или вообще оставить только вашу ветку, остальное вырезать, так как проект возможно уже бросили.

Спасибо за реинкарнацию!) И пожелание общего плана - приведите в порядок форк - включая readme, информацию, версию и т.п. (; Думаю сейчас сюда слетится народ.

**Comment by Jackal-1596** [comment]
Вроде бы работает пока. Встало корректно на Synology после удаления старой версии. Репа для обнов в настройках появился. Хотелочка. Строчка для введения стороннего API поиска есть, но нужно разъяснение как и где его получить и для чего он вообще. Желательно из оболочки плагина но из "ридми" тоже пойдёт.

**Comment by Jenstel** [comment]
> Вроде бы работает пока. Встало корректно на Synology после удаления старой версии. Репа для обнов в настройках появился. Хотелочка. Строчка для введения стороннего API поиска есть, но нужно разъяснение как и где его получить и для чего он вообще. Желательно из оболочки плагина но из "ридми" тоже пойдёт.

Неактуально. Для ключа убраны ограничения по запросам, поэтому можно пользоваться спокойно одним общим.

**Comment by spanchy** [comment]
Проверю - отпишусь. По ключу да, там нет лимитов на запросы. Но как вариант, на будущее, иметь возможность вбить свой, а если строка пустая то можно оставить "дефолтный" ваш.
