### ISSUE TITLE
[Feature request] Добавление иконок рейтинга, аналогично imdb

### ISSUE THREAD

**Issue by spanchy** [Jenstel/Kinopoisk.bundle#11]
Интересно было бы увидеть отображение рейтинга, как это сделано для imdb. Так же возможность отображать несколько рейтингов подряд - кинопоиск, imdb (напр.)

**Comment by Jenstel** [comment]
Скорее всего нет, судя по примеру других агентов одновременно отображается только один вид рейтингов
Найти бы полную документацию по метаданным Plex, тогда бы еще можно было подумать

**Comment by Jenstel** [comment]
Да так и есть, в метаданных есть только два тега rating и audienceRating и соответственно две картинки для них
