### ISSUE TITLE
[BUG] Не загружаются описания фильмов

### ISSUE THREAD

**Issue by DwarfRKA** [Jenstel/Kinopoisk.bundle#16]
Добрый день!

Не загружаются описания некоторых  фильмов (Олимпия 2 (1938), Исчезнувший (2021), Битва при Лонгтане (2019)).
Фильмы были определены, но загружены только название и год, иногда постер.
На Кинопоиске описание фильмов есть в полном объеме.
1. https://www.kinopoisk.ru/film/39424/
2. https://www.kinopoisk.ru/film/1436464/
3. https://www.kinopoisk.ru/film/262003/

![изображение](https://user-images.githubusercontent.com/92783956/137873919-f1cdeac8-7b66-4573-811f-ee1d735b2bf5.png)

Настройка агента:
![изображение](https://user-images.githubusercontent.com/92783956/137874144-cb093dd2-ad5a-4950-8614-6c00ca7ddb00.png)
![изображение](https://user-images.githubusercontent.com/92783956/137874221-bcd88f55-ae2b-4332-8a42-7006fc0e1528.png)

Пробовал отключать прокси в настройках агента и включать его на "sock5". На работу плагина, в моем случае, не влияет.
Перезагрузка сервиса ничего не меняет.

**Comment by baf28** [comment]
у меня таже проблема. Но прикол в том, что часть фильмов со временем поулчили описание, часть так и остались без описания. логика не прослеживается.

**Comment by DwarfRKA** [comment]
В моем случае, описание "со временем" не подтягивается, т.е. всё осталось на прежней позиции.
Более того, по мере добавления фильмов-мультфильмов, добавляются всё новые, у которых та же проблема.
Определяются, название, иногда постер (но добавление руками, после определения) скачивается, но не описание.

**Comment by IliaVM** [comment]
Тоже не загружаются. Фильм находится, но ничего не грузится

**Comment by baf28** [comment]
у меня таких фильмов всего 2, это Дюна и Война будущего, а у мультика Кощей Начало не подругажается постер ))). Остальные фильмы мои и мультики норм.

**Comment by Jenstel** [comment]
Проверьте еще раз на последней версии плагина.
У меня все работает
![image](https://user-images.githubusercontent.com/11753396/140888723-b5d18757-4de3-497b-b9eb-c53f7491bb11.png)

**Comment by DwarfRKA** [comment]
Спасибо! У этого фильма всё подгрузилось.

**Comment by IliaVM** [comment]
Фильм нашелся


![pic_5](https://user-images.githubusercontent.com/93448151/140912979-7fa5e22a-102e-4f25-b387-ce09fb5a6d5d.jpg)


Но ничего в итоге не загрузилось


![pic_4](https://user-images.githubusercontent.com/93448151/140913075-2bf40128-4bcd-4ab2-b450-18a296a7432f.jpg)


Хотя перед этим другой фильм загрузился нормально

**Comment by Jenstel** [comment]
> Фильм нашелся
> 
> ![pic_5](https://user-images.githubusercontent.com/93448151/140912979-7fa5e22a-102e-4f25-b387-ce09fb5a6d5d.jpg)
> 
> Но ничего в итоге не загрузилось
> 
> ![pic_4](https://user-images.githubusercontent.com/93448151/140913075-2bf40128-4bcd-4ab2-b450-18a296a7432f.jpg)
> 
> Хотя перед этим другой фильм загрузился нормально

Есть возможность выгрузить логи? 
"c:\Users\%USERNAME%\AppData\Local\Plex Media Server\Logs\PMS Plugin Logs\"

**Comment by IliaVM** [comment]
логи

[PMS Plugin Logs.zip](https://github.com/Jenstel/Kinopoisk.bundle/files/7505496/PMS.Plugin.Logs.zip)

**Comment by kurakinvit** [comment]
У меня такая же проблема сейчас.
Оборудование NAS Synology.
Операционная система - Synology DSM.
Версия Plex: 1.24.4.5081-6000.
Обновил плагин до последней версии 3.0.3 - всё равно: фильмы находит, но скачивает только название фильма и больше ничего.
На всякий случай выкладываю логи.
[logs.zip](https://github.com/Jenstel/Kinopoisk.bundle/files/7857756/logs.zip)

**Comment by Skaramush** [comment]
Подтверждаю проблему. Plex стоит на Windows, версия 1.39.1.2763-300bb607, версия плагина Kinopoisk - 3.0.3.
Для новых фильмов загрухается только название и год. Если несколько раз (обычно 2-3 раза) исправить сопоставление, то данные загружаются в полном объеме.

**Comment by hg-doublebug** [comment]
Я не нашел где в исходниках используется ключ полученный для апи кинопоиска
Может в этом косяк что все продолжают ходить под одним ключом и периодически получают отлуп.

**Comment by IliaVM** [comment]
Не, я не поленился, получил ключ, но результат тоже самый. Описание может загрузится со 2-3 раза, а может вообще не грузится.

**Comment by hg-doublebug** [comment]
я имел ввиду что не используется ключ который вводится в настройках.

**Comment by GritsanY** [comment]
[com.plexapp.agents.kinopoisk2.log](https://github.com/Jenstel/Kinopoisk.bundle/files/8029797/com.plexapp.agents.kinopoisk2.log)
@Jenstel Пока тема не закрылась, отпишусь сюда, похоже проблема тут та же, что и у меня - судя по логам, какая-то ошибка в обработке json при запросе трейлеров. У меня в настройках агента отключены трейлеры. Если у вас не получится быстро разобраться, почему не работает код обработки трейлеров, может, хотя бы сделаете так, чтобы запроса трейлеров вообще не было, если они отключены? Так хоть агент не будет падать и загрузка мета-данных пойдёт дальше. Спасибо за агент!

**Comment by hg-doublebug** [comment]
поставить лимит трейлеров 0 тогда будет отключено

**Comment by GritsanY** [comment]
> поставить лимит трейлеров 0 тогда будет отключено

Чёрт, была же мысль попробовать ноль в этом поле. Но логика упорно настаивала, что если в "Источник трейлеров" стоит "Отключено", то на лимит агент смотреть уже не будет. Да и "лимит в 0" для меня ассоциируется скорее со снятием ограничения на количество трейлеров. Ну ладно, просто потратил чуть больше своего времени из-за странной логики агента, всё равно ещё раз спасибо @Jenstel и @hg-doublebug !

**Comment by FFCRUS** [comment]
[com.plexapp.agents.kinopoisk2.zip](https://github.com/Jenstel/Kinopoisk.bundle/files/8484233/com.plexapp.agents.kinopoisk2.zip)
Плагин не находит фильмы ни по имени, ни по идентификатору kp-xxxxxxx. На всякий случай прикладываю лог. На примере этих фильмов:
https://www.kinopoisk.ru/film/1275401/
https://www.kinopoisk.ru/film/4396717/
Проверил через API тут, всё находит как по имени, так и по идентификатору: https://kinopoiskapiunofficial.tech/documentation/api/

**Comment by hg-doublebug** [comment]
@FFCRUS, Судя по логам это апи кинопоиска не ищет нормально (возвращает херню)
Тот же самый урл когда тестишь апи возвращает нормально

**Comment by FFCRUS** [comment]
@hg-doublebug Собственно, я это и написал: потестил API - возвращает корректно (как по имени, так и по идентификатору). А плагин возвращает хрень. Как по имени, так и по идентификатору кинопоиска. При этом, мой токен kinopoiskapiunofficial.tech прописан в плагине (и с ним я тестировал API). Причём проблемы с поиском по идентификатору я наблюдал и ранее, это старая проблема. Но чтобы вот совсем никак не искал (а по API корректно отдавал) я встретился впервые.

**Comment by hg-doublebug** [comment]
@FFCRUS, идентификатор прописан в настройках или в исходниках?
У меня эти косяки пропали после того как прописал в коде

**Comment by FFCRUS** [comment]
@hg-doublebug  Ключ API? В настройках плагина прописан. А куда в исходниках пихать его?

**Comment by hg-doublebug** [comment]
Kinopoisk.bundle\Contents\Libraries\Shared\kinoplex\const.py
меняем 'X-API-KEY'. Он там 2 раза встречается.

**Comment by FFCRUS** [comment]
Поменял. У меня, правда, это находится тут (Raspberry Pi OS lite x64):
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Kinopoisk.bundle/Contents/Libraries/Shared/kinoplex/const.py
Даже перезагрузился после этого. Ничего не изменилось.

**Comment by polkilo08** [comment]
У меня такая же проблема сейчас.
Оборудование NAS Synology.
Операционная система - Synology DSM.
Версия Plex: 1.32.0.6950-7000.
Плагин версии 3.0.3 - фильмы находит, но скачивает только название фильма и больше ничего.
На всякий случай выкладываю логи.
[Plex Media Server Logs_2023-04-20_13-36-02.zip](https://github.com/Jenstel/Kinopoisk.bundle/files/11285217/Plex.Media.Server.Logs_2023-04-20_13-36-02.zip)
Так же сделал:
Kinopoisk.bundle\Contents\Libraries\Shared\kinoplex\const.py
меняем 'X-API-KEY'.
Не помогло

**Comment by Jenstel** [comment]
Проблема подтверждена, неофициальный API не умеет нормально работать с трейлерами
Ставим количество трейлеров - 0 и снимаем галку "Грузить все видеоматериалы"
