### ISSUE TITLE
[BUG] Synology DS215j - Не отображается агент Кинопоиск

### ISSUE THREAD

**Issue by kurakinvit** [Jenstel/Kinopoisk.bundle#17]
**Описание ошибки**
У меня NAS Synology DS215j.
Установлена версия Plex 1.24.4.5081.

**Шаги для вопроизведения ошибки**
1. Перейти в 'Настройки' -> "Агенты"
2. По умолчанию выбран раздел 'Фильмы'
3. В списке агентов нет "Кинопоиск".

**Ожидание**
Ожидал увидеть агент "Кинопоиск" (также как отображаются агенты "Personal Media", "WikipediaRu".

**Скриншоты**
![plex01](https://user-images.githubusercontent.com/5922455/138603469-77325f83-19d5-4c76-a950-b46f115b1ee6.jpg)

**Характеристики сервера PLEX и версия агента КиноПоиск:**
 - OS: DSM 6.2.4-25556 Update 2
 - Браузер chrome
 - Версия PLEX 1.24.4.5081
 - Версия агента кинопоиск из файла VERSION: 663f5d8

**Comment by baf28** [comment]
отвечу за автора. вы добавили папку агента в папку плагинов? вы переименовали папку агента так что бы она заканчивалась на build ? (ну или что там в конце)

**Comment by kurakinvit** [comment]
> отвечу за автора. вы добавили папку агента в папку плагинов? вы переименовали папку агента так что бы она заканчивалась на build ? (ну или что там в конце)

Спасибо вам большое!
Не знал про требование, чтобы папка агента заканчивалась на bundle.
Переименовал - всё заработало.
Ещё раз спасибо!
