### ISSUE TITLE
[Not BUG] Вопрос по обновлениям

### ISSUE THREAD

**Issue by CJloHuK** [Jenstel/Kinopoisk.bundle#20]
Не знаю правильно ли было сюда написать или надо было в другое место...

Вопрос - в плагине есть настройка "репозитарий обновлений". Это подразумевает, что он сам автоматически обновляется? Или надо его обновлять вручную?

Так же не нашел, где можно в плагине посмотреть его версию. Может стоит добавить её куда-нибудь информационно?

**Comment by Jenstel** [comment]
Проверил автообновление, работает
1. Выбираем репозиторий jenstel
2. Выбираем канал обновления stable
3. Задаем интервал поиска обновлений (по дефолту 60 минут)
Плагин обновляется в фоновом режиме после сборки нового релиза
Новая версия плагина заработает ТОЛЬКО ПОСЛЕ ПЕРЕЗАПУСКА ПЛЕКСА

Добавил версию в описание плагина (кнопка i)

![image](https://user-images.githubusercontent.com/11753396/142403599-73efbad6-57ad-46f9-9d2d-b9fc7ad1f3f3.png)
