### ISSUE TITLE
[BUG] Плагин отсутствует в диалоговом окне "Сопоставить"

### ISSUE THREAD

**Issue by tref2me** [Jenstel/Kinopoisk.bundle#21]
**Описание ошибки**
Установил плагин конопоиска, api-ключ прописал.
Плагин положил сюда C:\Program Files (x86) \Plex\Plex Media Server\Resources\Plug-ins-c43dc0277
и сюда %LOCALAPPDATA%\Plex Media Server\Plug-ins (по инструкции), но отсюда плагин пропадает при перезапуске сервера.
Плагин появился в настройках плекса, но отсутствует в диалогах сопоставления. 

**Шаги для воспроизведения ошибки**
1. Переходим в библиотеку "Фильмы";
2. На обложке любого фильма нажать троеточие;
3. Выбрать "Исправить сопоставление";

**Ожидание**
В диалоге "Исправить сопоставление" в выпадающем списке "Автосовпадения" отсутствует плагин Кинопоиск
Если перейти в "Опции поиска", то в списке "Агент" плагин Кинопоиск отсутствует. 

**Скриншоты**
![изображение](https://user-images.githubusercontent.com/43093252/147883420-9f53ed0f-6de2-4095-8a0f-b4bedaddfb99.png)
![изображение](https://user-images.githubusercontent.com/43093252/147883431-04402719-305a-46d5-8d07-595000358b95.png)
![изображение](https://user-images.githubusercontent.com/43093252/147883441-219140bc-f6eb-4849-8e63-2738e7b42b6c.png)
![изображение](https://user-images.githubusercontent.com/43093252/147883596-268603e1-c074-4f0d-a084-2b6e8eb8aae3.png)

**Характеристики сервера PLEX и версия агента КиноПоиск:**
 - OS: Windows 10
 - Браузер Firefox
 - Версия PLEX 1.25.2.5319
 - Имя сервера: plex-media-server
 - Версия агента кинопоиск: Кинопоиск 2.0  вер 3.0.3

**Дополнительная информация**
Добавьте любой другой контекст о проблеме здесь.

**Comment by GritsanY** [comment]
Так вы в настройках самой библиотеки выбрали этот агент?

**Comment by tref2me** [comment]
Такие вещинадо в инструкции указывать. Спасибо, решено.
