### ISSUE TITLE
[NOT BUG] Время загрузки данных

### ISSUE THREAD

**Issue by alexab05** [Jenstel/Kinopoisk.bundle#23]
Доброе!
Подскажите, пжл, нормально ли явление, когда plex загружает данные с кинопоиска при сканировании библиотеки 10-15 фильмов за 10 часов. Ранее, до исправления всех багов - загрузка за 10 часов - штук 300.
Заранее благодарен за ответ.

Да, а так грузит все нормально - без ошибок, все определяет по тегу kp-

**Comment by Jenstel** [comment]
Проблема актуальна?

**Comment by alexab05** [comment]
Спасибо, нет актуальность потеряна. Само собой plex стал работать нормально. Сейчас вообще летает...
Может дело было в кинопоиске...
