### ISSUE TITLE
[BUG] Не удаётся подружить Kinopoisk.bundle 3.0.3 и PMS 1.28.0.5999

### ISSUE THREAD

**Issue by ffcrus** [Jenstel/Kinopoisk.bundle#26]
**Описание ошибки**
На последней версии сервера не удаётся подключить плагин так, чтобы он заработал. То ли лыжи не едут, то ли я ...

**Шаги для вопроизведения ошибки**
1. Устанавливаем последнюю версию Plex Media Server (в docker, из официального репозитория [plexinc/pms-docker](https://hub.docker.com/r/plexinc/pms-docker))
2. Создаём библиотеку
3. Загружаем плагин в нужную папку
4. Перезагружаем PMS
5. Видим в списке плагинов Kinopoisk, но не можем им воспользоваться

**Ожидание**
При сопоставлении фильмов раньше была возможность сделать "Кинопоиск 2.0" первым в списке агентов и в любой момент выбрать его вручную, теперь это не так.

**Скриншоты**
Плагин установлен и виден в системе, все настройки внутри можно настраивать, ключи к kinopoiskapiunofficial.tech и anti-captcha.com введены:
https://i.imgur.com/YRSeZs9.png
Плагин включен везде, где только можно:
https://i.imgur.com/H4ePdTJ.png
https://i.imgur.com/UPLe1c7.png
https://i.imgur.com/1SUOUMe.png
Ни с одним из агентов или сканнеров,
https://i.imgur.com/hgJTOAs.png
https://i.imgur.com/pHwI7yy.png
не удаётся увидеть Кинопоиск 2.0, как было раньше (это весь дроплист):
https://i.imgur.com/zagHmf8.png
https://i.imgur.com/K902gq6.png

**Характеристики сервера PLEX и версия агента КиноПоиск:**
 - OS: [Raspberry Pi OS lite (64 bit) 5.15.56-v8+ #1575 {Debian GNU/Linux 11 (bullseye) 11.4}]
 - Браузер [Mozilla FireFox for Ubuntu 102.1.0esr (64 бита)]
 - Версия PLEX [1.28.0.5999]
 - Имя сервера [Pi4Plex]
 - Версия агента кинопоиск [3.0.3]

**Дополнительная информация**
Создаётся ощущение, что в Plex внедрили новый агент "[plex movie](https://support.plex.tv/articles/advanced-settings-plex-movie-agent/)", с которым не совместим плагин. И данные для фильмов качаются совсем не с Кинопоиска. Как и настройки показывать рейтинги в описании не отработали:
https://i.imgur.com/20XfiWH.jpg
Вот как настроено в плагине:
https://i.imgur.com/8ql9T6L.png

**Comment by Jenstel** [comment]
Проблема актуальна?

**Comment by GoodwinSan** [comment]
> Проблема актуальна?

актуальна. отдельный баг заведён выше о том что не подгружаются данные

**Comment by ffcrus** [comment]
> Проблема актуальна?

Нет, решилась сама собой когда-то, не могу сказать с каким из обновлений PMS. Пошёл убедиться, что проблема актуальна, но сейчас работает корректно. Вот такая сейчас у меня конфигурация:

OS: [Raspberry Pi OS lite (64 bit) 6.1.21-v8+ #1642 {Debian GNU/Linux 11 (bullseye) 11.7}]
Браузер [Mozilla FireFox for Ubuntu 102.10.0esr (64 бита)]
Версия PLEX [1.32.2.7100]
Имя сервера [Pi4Plex]
Версия агента кинопоиск [3.0.3] (#663f5d8)

Вот он нв настройках библиотеки:
https://i.imgur.com/Qkiw2c6.png

Вот он в поиске:
https://i.imgur.com/qOD2szg.png
