### ISSUE TITLE
[BUG] Terramaster TOS 5.1, Plex, Сопоставление - Совпадений не найдено.

### ISSUE THREAD

**Issue by lugovskovp** [Jenstel/Kinopoisk.bundle#31]
**Описание ошибки**
Подробное описание ошибки. Какие были произведены действия.

**Шаги для вопроизведения ошибки**
1. Перейти в Сериалы.' 
2. Нажать 'Свойства'(три точки)
3. Выбрать 'Сопоставить...'
4. "Расположение: /Volume1/pub...Media/Serials/Mastodont.S01.2023.WEB-DL.1080p", Совпадений не найдено.
5. Вручную, опции поиска:
6. Название Мастодонт (сериал)
7. Агент Кинопоиск 2.0
8. Поиск
9. Результат - совпадений не найдено

**Ожидание**
На сайте кинопоиска сериал заведомо есть: https://www.kinopoisk.ru/series/5257256/

**Скриншоты**
![image](https://github.com/Jenstel/Kinopoisk.bundle/assets/45869072/c912d4a0-119f-4d5e-a6db-8c2406426501)
![image](https://github.com/Jenstel/Kinopoisk.bundle/assets/45869072/e9e39830-f2ff-433b-b135-94d940b8957c)
![image](https://github.com/Jenstel/Kinopoisk.bundle/assets/45869072/df9ac316-3ae8-4e7b-a4ed-eaf5e80b825d)

**Характеристики сервера PLEX и версия агента КиноПоиск:**
 - HW: TerraMaster F4-423 NAS
 - OS: TerraMaster  TOS 5.1.67
 - Браузер [прим. chrome, safari]
 - Версия PLEX: 1.32.7.7621 
 - Имя сервера : PlexC540
 - Версия агента кинопоиск:  Kinopoisk #663f5d8

**Дополнительная информация**
Plex path: /Volume1/@apps/.plex/plexmediaserver/
Plugin path: /Volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Kinopoisk.bundle
Ключ API в настройках плагина введён.
Лог Kinopoisk.bundle прилагаю (старт 17:05, затем в 17:25 запрос на поиск "Мастодонт (сериал)", 0 результатов.

[com.plexapp.agents.kinopoisk2.log](https://github.com/Jenstel/Kinopoisk.bundle/files/13536595/com.plexapp.agents.kinopoisk2.log)

**Comment by Jenstel** [comment]
Данный плагин не адаптирован для сериалов, используйте рекомендуемый от Plex, он работает прекрасно

**Comment by lugovskovp** [comment]
Родной Plex-овый как раз для сериалов - нон вагитта, нон рота когорта. 
А вот как раз данный по кинопоиску гораздо лучше родного сериалы смотрит.
Да собственно проблему я практически решил - спасибо, что Питон - кинопоиск и api поменял слегка, что-то вообще убрал, что-то добавил. Что ещё не решил - не работает пока автосопоставление. 
Надо руками запускать "Сопоставить" - тогда отрабатывает, и артистов и обои. До автоскоринга всё руки не доходят.
