### ISSUE TITLE
[BUG]Иногда подкачивает некорректные постеры

### ISSUE THREAD

**Issue by p-p-stepanov** [Jenstel/Kinopoisk.bundle#5]
![image](https://user-images.githubusercontent.com/91959926/136032090-ade0daae-cf0a-4304-9529-29fa4eeccb99.png)

**Comment by spanchy** [comment]
Сопоставление исправлять можно, там есть выбор постеров. И у вас возможно стоит выбор постеров по качеству, а не по локализации.

**Comment by p-p-stepanov** [comment]
Совсем от другого фильма в данном случае тянет.

Причем притянул много, и все от другого.

вт, 5 окт. 2021 г., 22:04 Alexander Lipatov ***@***.***>:
